openapi: 3.0.0
info:
  title: Chatbot API
  version: 1.0.0
  description: API for interacting with the RAG chatbot to ask questions about book content.
paths:
  /chatbot/ask:
    post:
      summary: Ask a question to the RAG chatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: Authenticated user ID
                query_text:
                  type: string
                  description: The user's question
                chapter_id:
                  type: string
                  description: Optional chapter context ID
      responses:
        '200':
          description: Successful response from chatbot
          content:
            application/json:
              schema:
                type: object
                properties:
                  response_text:
                    type: string
                  source_content_ids:
                    type: array
                    items:
                      type: string
        '400':
          description: Invalid query or missing user ID
        '500':
          description: Internal server error or chatbot processing failure